import { Inter } from "next/font/google";
import "./globals.css";
import PixelTrailCanvas from "@/components/PixelTrail";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <PixelTrailCanvas 
        pixelSize={18} // Change the pixel size
        pixelColor="255, 0, 0" // Change the pixel color to red (RGB format)
        trailLength={50} // Change the number of pixels in the trail
        fadeSpeed={0.1} // Change the fade speed of the pixels
        maxDistance={100} // Change the max distance for pixels to disappear
      />
        {children}</body>
    </html>
  );
}
